### ISSUE TITLE
Travis secure env vars read?

### ISSUE THREAD

**Issue by goors** [ktomk/run-travis-yml#7]
Hi,

since this is running on Github is there a way to use Travis CI env secure vars?
Or I have to redefine all env vars in Github actions secrets?

**Comment by ktomk** [comment]
Yes, more or less.

What we have done in the past was to make secrets "optional" so that things failed not at setup but at use/access (e.g. not decrypting a key if the password is n/a) so it became clear which builds depend on secrets and until where we could just run without any.

**Comment by goors** [comment]
Thanks.
